[context.production.environment]
  YARN_VERSION = "1.22.4"
  NODE_VERSION = "12"
  API_HOST = "https://tchak-a-heroic-death-game.builtwithdark.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
